### ISSUE TITLE
using tea magic with Makefile

### ISSUE THREAD

**Issue by ddobrinskiy** [pkgxdev/pkgx#430]
Is it expected that tea magic does not work with `make`?

My Makefile:
```makefile
echo:
	pipx run pycowsay "Hello World"
```

failed commands:
```bash
❯ make echo
pipx run pycowsay "Hello World"
/bin/sh: pipx: command not found
make: *** [echo] Error 127
```

This runs of course, but I was expecting magics to work out of the box
```
❯ tea +gnu.org/make +pypa.github.io/pipx make echo
pipx run pycowsay "Hello World"

  -----------
< Hello World >
  -----------
   \   ^__^
    \  (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
```

also this works as well:

```
❯ tea +pypa.github.io/pipx make echo
pipx run pycowsay "Hello World"

  -----------
< Hello World >
  -----------
   \   ^__^
    \  (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
```

**Comment by mxcl** [comment]
Yes this is expected (and I believe documented). tea’s magic only works at a terminal prompt. Though in scripts you can import the magic, you do need to do that manually.

Partly this is just how this stuff works. The shell deliberately doesn't propagate the hooks we create to sub processes. And partly it's how other tools work.

In general though, this is probably correct. It would be potential anarchy otherwise. Maybe.

All the same, I have plans on how to provide solutions for all of these. And am planning on building them. Magic, magic everywhere!

**Comment by mxcl** [comment]
For now just prepend everything inside the Makefile with `tea`

**Comment by lino-levan** [comment]
I'd really love to have magic in makefiles (especially since at work I can't expect everyone to switch over to tea just yet!). No idea how this would be implemented technically.

**Comment by jhheider** [comment]
I think the two methods you could use today are:
- use a `tea` env outside the makefile to provide the tools used in the makefile
- _possibly_ you can define a TEA function in your makefile that is `tea` if it's present and "" otherwise, and then decorate commands as `$TEA cp file foo bar/`.

**Comment by 4brunu** [comment]
Hi, I have the same issue.

I want to force magic to reload the `.tea.yaml` on the git hook `post-checkout`, to ensure the I'm using the correct version of each tool mentioned in the `.tea.yaml`.

Doing `cd .` in the terminal works, but not on the Makefile, nor on a script file.

Is there any way to force maging to reload the `.tea.yaml`?

Thanks

**Comment by michaelessiet** [comment]
I think 
```make
echo:
	pkgx pipx run pycowsay "Hello World"
```
would proper usage.

This issue has been stale for a while so I think it's safe to close
