### ISSUE TITLE
Docs regarding Docker might be incorrect

### ISSUE THREAD

**Issue by aberres** [pkgxdev/pkgx#804]
I am right now trying to figure out what is the best way to make some packages available in Docker images.

Before v1 we were doing some hackery with `dev` and a manually tweaked PATH.
Now that we have a stable release, it was time to revisit the official recommendations.

I tried to follow the docs but somehow failed.

The simple 

```dockerfile
FROM pkgxdev/pkgx
RUN env +node@16
RUN npm start
```

results in 

```
 > [ 2/15] RUN env +node@16:
#0 0.092 env: '+node@16': No such file or directory
------
Dockerfile:2
--------------------
   1 |     FROM pkgxdev/pkgx
   2 | >>> RUN env +node@16
   3 |     RUN npm start
   4 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c env +node@16" did not complete successfully: exit code: 127
```

The same happens when trying to use `RUN eval "$(curl -Ssf --proto '=https' https://pkgx.sh)"`

As we see, the used shell is `/bin/sh`. Can this work at all?

**Comment by mxcl** [comment]
My bad, I just naively assumed this would work since the same commands work if you run the image interactively.

I have played around and the instructions seem to work provided you set

```Dockerfile
SHELL ["bash", "-ic"]
```

Which is hardly ideal, but at least this will do as a workaround for now. Will update docs.

Hopefully we can figure out a better solution. Our shellcode *does* work for POSIX mode shell. Some parts do not but everything you would need in a typical `Dockerfile` does. It's just a matter of configuring the docker image to load the shellcode as part of the image. And come to think of it, that shouldn't be too hard.

**Comment by mxcl** [comment]
Edit: k so every RUN step is its own shell just like GitHub Actions. In GitHub Actions we know how to amend the environment anyway, but in Docker this is not exposed as a general solution.

We could edit `/etc/profile` probs to add env.

In the meantime the solution is

```Dockerfile
SHELL ["bash", "-ic"]
RUN env +node && npm start
```

I believe I can make it work without changing the shell, but making it so our shellcode commands like `env` and `dev` work in docker will require more work.

I'm willing to do the work though. It will be impossible to make it work in every docker sadly, but we can certainly have it work in 95% of default images with some POSIX compliant work.

I'll update our docs to include this data, thanks for the report and sorry for the promises that I hadn't tested.

**Comment by aberres** [comment]
Thanks, and no worries!

I'm looking forward to using pkgx more and more.

**Comment by mxcl** [comment]
> I'm looking forward to using pkgx more and more.

That's great to hear 😌. Let us know what you need!
