### ISSUE TITLE
Package download speeds can be improved

### ISSUE THREAD

**Issue by kishaningithub** [pkgxdev/pkgx#834]
I am working with an internet speed whose download speed clocks to ~350 Mbps but when a package is being download by pkgx for example as a result of `pkgx aws --version` command it goes only till ~700 Kbps at max.

If there can be some guidance i can start working on PRs to speedup the downloads.

**Comment by mxcl** [comment]
the logic happens in https://github.com/pkgxdev/libpkgx/blob/main/src/plumbing/install.ts

I'm not surprised it is capped because the pipeline logic of http -> store-file -> tar x -> sha is serial rather than parallelized. However it maxed out my bandwidth so was happy.

so should be an easy fix of using one of deno’s better pipelining systems more effectively.

Note that part of the reason it is this way is because we convert the code to a node package via deno’s DNT tool. However if you want to work on this I am happy to fix that part.

Thanks for the consideration and help.

**Comment by michaelessiet** [comment]
I'm assuming this is solved because I'm getting near max download speeds. Safe to close?

**Comment by kishaningithub** [comment]
I am also getting improved speeds.. not really sure which is the fix which made this a happen.

I think this can be closed for now
