### ISSUE TITLE
warn: parse failure: bitcoin.org

### ISSUE THREAD

**Issue by fredrikaverpil** [pkgxdev/pkgx#982]
Today I started seeing this error in my terminal when entering a project with `dev` activated.

```bash
cd projectx
warn: parse failure: bitcoin.org
warn: parse failure: bitcoin.org
env +go.dev~1.21 +npmjs.com +git-scm.org

rm pkgx.yml
cd ..
env -go.dev~1.21 -npmjs.com -git-scm.org
warn: parse failure: bitcoin.org
warn: parse failure: bitcoin.org
warn: parse failure: bitcoin.org

cd projectx
env +go.dev +git-scm.org

cd ..
env -go.dev -git-scm.org
warn: parse failure: bitcoin.org
warn: parse failure: bitcoin.org
```

An org-wide search for `bitcoin`: https://github.com/search?q=org%3Apkgxdev+bitcoin&type=repositories

I have to be frank here and say I'm not super happy to see something is trying to potentially reach out to bitcoin.org from my machine...

**Comment by jhheider** [comment]
Don't worry, nothing in our code contacts `bitcoin.org`. What has likely happened is the package file for the bitcoin server (named: `bitcoin.org` > https://github.com/pkgxdev/pantry/blob/main/projects/bitcoin.org/package.yml) is likely corrupt in your pantry. Running `pkgx --sync` should re-download the pantry (you can review the whole thing in that repository if you're concerned, but it's all YAML files that describe how to build/test the software we provide).

It could have happened to any file in the pantry, and is almost certainly a coincidence that it's that specific package. @mxcl is tracking reports of pantry corruption (these have gone down significantly as we've improved synchronization methods), so he might have further questions.

Obviously, since our software is open source, you can search this repository and pkgxdev/libpkgx if you still have concerns, but I can assure you we have not implemented any code to contact bitcoin.org, which is just the homepage for the bitcoin core project.

**Comment by fredrikaverpil** [comment]
Thanks @jhheider, I'll try the sync command. I see now that there's been other reports of this parse failure too.

**Comment by fredrikaverpil** [comment]
Yes, `pkgx --sync` fixed it. 👍

**Comment by jhheider** [comment]
It should sync periodically, but if a sync is broken, it might be a bit before the next one.
